### ISSUE TITLE
please clarify license on included components

### ISSUE THREAD

**Issue by yarikoptic** [NIRALUser/DTIPrep#15]
since I guess DTIPrep != NeuroLib, I can't simply "apply" Apache 2.0 license to the files from NeuroLib project which carry no statement of the license, thus "all rights are reserved" and nothing is permitted according to those files headers, e.g.

```
Program:   NeuroLib
Module:    $file: itkDWICropper.h $
Language:  C++
Date:      $Date: 2009-11-26 21:52:35 $
Version:   $Revision: 1.4 $
Author:    Zhexing Liu (liuzhexing@gmail.com)

Copyright (c) NIRAL, UNC. All rights reserved.
See http://www.niral.unc.edu for details.

This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
```

BTW link on http://www.med.unc.edu/psych/research/niral/download/download-software  for "Non-supported Software: NeuroLib download page" leads to N/A  http://www.ia.unc.edu/dev/tutorials/index.php

**Comment by juanprietob** [comment]
Thank you for pointing this out. 
I have edited the files containing the ambiguous license description pull https://github.com/NIRALUser/DTIPrep/pull/16. 
The License is described in the root folder, i.e., License.txt and applies to the whole project.

**Comment by yarikoptic** [comment]
And who is the copyright holder?  license without owner/copyright holder is like a driver license without having any car to drive.  That templated License.txt has "Copyright [yyyy] [name of copyright owner]" which you might like to adjust for that matter I guess

**Comment by juanprietob** [comment]
Indeed, It has been modified.
