### ISSUE TITLE
Gradients excluded during Interlace Check though thresholds not exceeded

### ISSUE THREAD

**Issue by BrittanyRHowell** [NIRALUser/DTIPrep#23]
Gradients are being excluded when running the InterlaceWise check. The user specified thresholds are not exceeded, so it is unclear why they are being excluded. Example QC report attached.
[116845_01_79dir_topup_corrected_QCReport.txt](https://github.com/NIRALUser/DTIPrep/files/307806/116845_01_79dir_topup_corrected_QCReport.txt)

**Comment by styner** [comment]
The gradient is being excluded as it's z-score is too low (which is computed as (actual correlation - mean correlation) / standard deviation over all correlation. Please increase the Deviation threshold
