### ISSUE TITLE
precision reporting wrong

### ISSUE THREAD

**Issue by styner** [NIRALUser/DTIPrep#43]
in src/itkDWIBaselineAverager.hxx

" << std::setw(9) << std::setiosflags(std::ios::fixed) << std::setprecision(17) << std::setiosflags( std::ios::right | std::ios::scientific )"

setw and setprecision should be aligned, particularly if one chooses a fixed notation (setw should be larger than setprecision). And if one choses a fixed notation, then one should not use scientific. So this is clearly not good programming on our end. 

The best seems to replace this with a fixed notation at the higher precision (probably too high with 17), i.e. 
" << std::setw(19) << std::setiosflags(std::ios::fixed) << std::setprecision(17) << std::setiosflags( std::ios::right)"

**Comment by hjmjohnson** [comment]
I'd recommend using " itk::NumberToString<double> DoubleConvert;"  

https://itk.org/Doxygen/html/classitk_1_1NumberToString.html

This will minimize the size of what is printed without excessively printing too much information.

**Comment by styner** [comment]
Great, thanks, will do.

**Comment by juanprietob** [comment]
All the float values are format using NumberToString from ITK now in version 1.2.9. [commit](https://github.com/NIRALUser/DTIPrep/commit/d76440973fb9b2afd223597080dccdc8a1447775)
