### ISSUE TITLE
DTIPrep data type output

### ISSUE THREAD

**Issue by mriedel56** [NIRALUser/DTIPrep#53]
I converted DICOMs to a .nrrd file, and found that the data type was "short". After running DTIPrep, the resulting .nrrd file has data type "unsigned_short". This prevents Slicer (4.8.1) from being able to convert from Nrrd to FSL format. Is there any way to specify the output data type during a call to DTIPrep from the command line, or convert the data type of a .nrrd file?

**Comment by styner** [comment]
Thanks for the comment. The original DICOM data should be in unsigned short (raw MRI data should not have negative values). I don't think though that this should be the issue if you are not able to convert from NRRD to FSL (as we are doing so regularly without a problem, using unsigned short data). Still, if you are interested in converting the data type of a nrrd file, you can use the "unu" tool distributed with Slicer. unu is a swiss army knife kinda tool for nrrd files and can do a lot of operations. For type conversions you would need to do (via terminal):
unu convert -t short -i input.nrrd -o output.nrrd
Best Martin
