### ISSUE TITLE
DTIPrep without X11?

### ISSUE THREAD

**Issue by SyamGadde** [NIRALUser/DTIPrep#8]
We have been using v1.1.6 of DTIPrep with no problems.  We wanted to try v1.2.4 to see if some outstanding issues had been addressed.  Unfortunately it seems we can't run the newer version without X, even if we are using a protocol file and don't need the GUI.  We are running this under SGE so jobs are submitted to a cluster and X is not available to us.  Any ideas?

**Comment by fbudin69500** [comment]
Hello,
You should still be able to run DTIPrep without a GUI being shown even with DTIPrep1.2.4. Here is what your command line should look like:
DTIPrep --xmlProtocol ~/my_protocol.xml --DWINrrdFile myDWI.nrrd --outputFolder result/ -c

**Comment by SyamGadde** [comment]
Thank you -- the -c option was not necessary before (and still says it is default in the help message).  That fixes it.

**Comment by fbudin69500** [comment]
Thanks for the report. I will update the help.
